// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-QBRAbdXUyRQ-xnSu-rBLKeuhVRePgiY',
    appId: '1:1068270161249:web:58c9d4104deed9750a0920',
    messagingSenderId: '1068270161249',
    projectId: 'chatbotfirebase-dcefc',
    authDomain: 'chatbotfirebase-dcefc.firebaseapp.com',
    storageBucket: 'chatbotfirebase-dcefc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTPobqlw3KTgUFmLDf75xlqhabtl-Mp98',
    appId: '1:1068270161249:android:260a12a3693e50ab0a0920',
    messagingSenderId: '1068270161249',
    projectId: 'chatbotfirebase-dcefc',
    storageBucket: 'chatbotfirebase-dcefc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBso1y4tefuAmazsA1bUPlKqKs2lmwTxiY',
    appId: '1:1068270161249:ios:d3f0af473ca5a9e90a0920',
    messagingSenderId: '1068270161249',
    projectId: 'chatbotfirebase-dcefc',
    storageBucket: 'chatbotfirebase-dcefc.firebasestorage.app',
    iosBundleId: 'com.example.chatbotFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBso1y4tefuAmazsA1bUPlKqKs2lmwTxiY',
    appId: '1:1068270161249:ios:d3f0af473ca5a9e90a0920',
    messagingSenderId: '1068270161249',
    projectId: 'chatbotfirebase-dcefc',
    storageBucket: 'chatbotfirebase-dcefc.firebasestorage.app',
    iosBundleId: 'com.example.chatbotFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-QBRAbdXUyRQ-xnSu-rBLKeuhVRePgiY',
    appId: '1:1068270161249:web:a38756ba80c615db0a0920',
    messagingSenderId: '1068270161249',
    projectId: 'chatbotfirebase-dcefc',
    authDomain: 'chatbotfirebase-dcefc.firebaseapp.com',
    storageBucket: 'chatbotfirebase-dcefc.firebasestorage.app',
  );
}
